apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
  namespace: kube-system
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
      path: /cluster_volume/elastic/data