apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb
  namespace: kube-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
      path: /cluster_volume/influxdb/data